# Generated by Django 5.1.1 on 2024-10-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuerpo', models.TextField()),
                ('califacacion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ('califacacion',),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publicado',)},
        ),
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.ManyToManyField(to='posts.comentario'),
        ),
    ]
